// Render each character as a separate page for SVG export
#import "../lib.typ": *

#let sz = 128pt
#set page(width: sz, height: sz, margin: 0pt, fill: none)

#align(center + horizon, bob(size: sz))
#pagebreak()
#align(center + horizon, alice(size: sz))
#pagebreak()
#align(center + horizon, christina(size: sz))
#pagebreak()
#align(center + horizon, mary(size: sz))
#pagebreak()
#align(center + horizon, eve(size: sz))
#pagebreak()
#align(center + horizon, frank(size: sz))
#pagebreak()
#align(center + horizon, grace(size: sz))
#pagebreak()
#align(center + horizon, trent(size: sz))
#pagebreak()
#align(center + horizon, mallory(size: sz))
#pagebreak()
#align(center + horizon, victor(size: sz))
#pagebreak()
#align(center + horizon, ina(size: sz))
#pagebreak()
#align(center + horizon, murphy(size: sz))
#pagebreak()
#align(center + horizon, bella(size: sz))
#pagebreak()
#align(center + horizon, bolt(size: sz))
#pagebreak()
#align(center + horizon, pixel-char(size: sz))
#pagebreak()
#align(center + horizon, crank(size: sz))
#pagebreak()
#align(center + horizon, nova(size: sz))
#pagebreak()
#align(center + horizon, sentinel(size: sz))
#pagebreak()
#align(center + horizon, alien(size: sz))
#pagebreak()
#align(center + horizon, seraphim(size: sz))
#pagebreak()
#align(center + horizon, shamir(size: sz))
#pagebreak()
#align(center + horizon, steve(size: sz))
#pagebreak()
#align(center + horizon, yui(size: sz))
#pagebreak()
#align(center + horizon, logic(size: sz))
#pagebreak()
#align(center + horizon, tabby(size: sz))
#pagebreak()
#align(center + horizon, schrodinger(size: sz))
#pagebreak()
#align(center + horizon, enaga(size: sz))
#pagebreak()
#align(center + horizon, noir(size: sz))
#pagebreak()
#align(center + horizon, milady(size: sz))
#pagebreak()
#align(center + horizon, tigris(size: sz))
#pagebreak()
#align(center + horizon, porcellum(size: sz))
#pagebreak()
#align(center + horizon, lain(size: sz))
#pagebreak()
#align(center + horizon, dragon(size: sz))
#pagebreak()
#align(center + horizon, paddler(size: sz))
#pagebreak()
#align(center + horizon, chaser(size: sz))
#pagebreak()
#align(center + horizon, alchemist(size: sz))
